repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        exclude: ^sources/managed/
      - id: end-of-file-fixer
        exclude: ^sources/managed/
      - id: trailing-whitespace
        exclude: ^sources/managed/
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: ["--select", "F", "--fix"]
        files: ^(scripts|tests)/.*\.py$
      - id: ruff-format
        files: ^(scripts|tests)/.*\.py$